version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REPO_URI: "194526776035.dkr.ecr.us-east-1.amazonaws.com/mysample_appecr"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-sample-app .
      - docker tag my-sample-app:latest $ECR_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"mysample-app","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

